### ISSUE TITLE
Missing notify and rssi methods

### ISSUE THREAD

**Issue by tempestwf** [somq/ionic-plugin-bluetoothle#2]
Hi Somq

I really like what you have done here and I would like to use it, however, it's missing the notify and rssi methods.

I was wondering if you had any plans to include these, and if so in what time frame? Looking for a solution as soon as possible.

Thanks very much.

Will

**Comment by somq** [comment]
Hi, I won't be able to work on this plugin very soon unfortunately. I'm planning to wrap any method of cordova-plugin-bluetoothle and I should be back on it probably this summer.
But eventually you can make a pull request and will take the time to look into it.

[RSSI](https://github.com/somq/ionic-plugin-bluetoothle/blob/master/dist/%40ionic-native/bluetooth-le/index.js#L146)

[Notify](https://github.com/somq/ionic-plugin-bluetoothle/blob/master/dist/%40ionic-native/bluetooth-le/index.js#L224)

**Comment by tempestwf** [comment]
Thanks for the update somq. After consideration and I think I may have figured out some workarounds for needing those 2 methods. Thanks for building a great wrapper.

All the best

Will

**Comment by somq** [comment]
Your welcome Will!

**Comment by somq** [comment]
@tempestwf I made a PR on ionic-native repo which now has all the available methods wrapped if you still need this.
https://github.com/ionic-team/ionic-native/pull/2651

**Comment by tempestwf** [comment]
Hi Somq

That's great. Thanks for letting me know.

We ended up writing a custom wrapper to implement all the methods, but we
will switch to the official one in the future.

All the best

Will

**Comment by somq** [comment]
Hi @tempestwf,

Nice to know you that you worked on your own wrapper.
Maybe you could take some time to take a look at the the [current source of the official wrapper](https://github.com/somq/ionic-native/blob/master/src/%40ionic-native/plugins/bluetooth-le/index.ts) and compare it with yours. 
Maybe you will see something I missed...

**Comment by tempestwf** [comment]
Hi Somq

I reviewed your version and my side by side. You did an awesome job! There
wasn't anything I could find that was missing from it at all, and yours is
much better constructed than mine is.

We will be moving over to using it.

Thanks for making such a complete wrapper.

All the best

Will

**Comment by somq** [comment]
Hi Will,

Thanks for your review.
Do not hesitate if you have any further recommandation in the future.

**Comment by tempestwf** [comment]
Will do.

Thanks again.

Will
