### ISSUE TITLE
initializePeripheral is broken

### ISSUE THREAD

**Issue by jaco-terbraak** [somq/ionic-plugin-bluetoothle#3]
initializePeripheral returns a Promise<{...}>, which is used as callback for any incoming data on the Gatt server. However, Promise allows invocation of the then()-callback only once, which will make it work the first time, but not for subsequent callbacks. Therefore it will trigger a callback to say that initializePeripheral succeeded, but after that the callback is never triggered again.

The fix is to change the return type in https://github.com/somq/ionic-plugin-bluetoothle/blob/1c4ed9dc482d002ef6d57aa5d6fb501b4d2ad934/dist/%40ionic-native/bluetooth-le/index.d.ts#L237 to Observable<{...}>, which does support multiple callback invocations.

**Comment by somq** [comment]
I think you are right, I can't test right now though.
ref: https://github.com/randdusing/cordova-plugin-bluetoothle#initializeperipheral

It feels a bit not intuitive to me because *"initialize"* usually refers to a 1 time action with only 1 callback needed.

Merged your PR, thanks.

**Comment by jaco-terbraak** [comment]
Thanks. I've tested this with actual hardware, and can confirm it works.

I agree that the naming is a bit misleading, I suspect it was a shortcut taken by the Cordova plugin developer.

**Comment by somq** [comment]
Alright, will dig into that when I'm going back to this plugin.
Thank you @jaco-terbraak

**Comment by curious-monggo** [comment]
This... this <3. You sir, are a lifesaver! Btw, it would do you good if you specify the methods available right on the readme as how randdusing does. Maaan, I almost skipped this one because I thought this doesn't support peripheral mode, All hail somq~!

**Comment by curious-monggo** [comment]
I really hope this plugin gets more support from the ionic community :+1:

**Comment by somq** [comment]
Hi @laaaaanceeee ,
Your welcome, glad it can help!

I've just made a pull request on ionic-native repo.
https://github.com/ionic-team/ionic-native/pull/2651

It contains any available methods and all of them are documented!
Feel free to test it.

Tomorrow I will update this repo btw
