### ISSUE TITLE
Function stringToBytes() has inverse signature

### ISSUE THREAD

**Issue by maske94** [somq/ionic-plugin-bluetoothle#6]
Hi @somq ,

Here maske94 again :) I'm working kind of intensively with your plugin recently, and I renew my compliments for your work.

I think I found another small oversight in the last version of the plugin from ionic native ( @ionic-native/bluetooth-le/ngx ).

According to its name, the function ` stringToBytes()` should accept a `string` type as parameter and return a `Uint8Array` type.

Instead, it seems to do the opposite: ` stringToBytes(value: Uint8Array): string`
Can you kindly look into it?

Thank you for the support.

**Comment by somq** [comment]
Hi,
Thanks for the feedback. 
You are right, I guess it was a copy/pasta mistake.

I opened a new PR on the ionic-native repo fixing these issues (including this one):
https://github.com/somq/ionic-native/projects/1

Feel free to open a new issue if you find anything else wrong. I will be working intensively with the plugin/wrap aswell and will try to make it as reliable as it can be.
i'm closing this one.
